-- ============================================================
-- Wakala Admin Setup
--
-- Run this in the Supabase SQL editor to install the admin role,
-- user-role checks, and admin balance management functions.
-- ============================================================

create or replace function public.is_active_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users au
    join public.admin_roles ar on ar.id = au.role_id
    where au.user_id = auth.uid()
      and au.status = 'active'
      and ar.name in ('super_admin', 'admin', 'moderator')
  );
$$;

create or replace function public.get_admin_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select ar.name
  from public.admin_users au
  join public.admin_roles ar on ar.id = au.role_id
  where au.user_id = auth.uid()
    and au.status = 'active'
  limit 1;
$$;

create or replace function public.is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users au
    join public.admin_roles ar on ar.id = au.role_id
    where au.user_id = auth.uid()
      and au.status = 'active'
      and ar.name = 'super_admin'
  );
$$;

create table if not exists public.admin_roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  permissions jsonb default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_roles enable row level security;

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  role_id bigint not null references public.admin_roles(id) on delete restrict,
  status text not null default 'active' check (status in ('active', 'inactive', 'suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

create or replace function public.update_admin_users_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists update_admin_users_timestamp on public.admin_users;
create trigger update_admin_users_timestamp
before update on public.admin_users
for each row execute function public.update_admin_users_timestamp();

-- Seed default admin roles
insert into public.admin_roles (name, description, permissions) values
  ('super_admin', 'Full system access', '["all"]'::jsonb),
  ('admin', 'Standard admin access', '["users", "balances", "esim", "creators"]'::jsonb),
  ('moderator', 'Content moderation', '["creators", "review"]'::jsonb)
on conflict (name) do nothing;

-- Admin table policies
create policy "Admins can view admin users"
  on public.admin_users
  for select
  using (public.is_active_admin());

create policy "Only super admins can update admin status"
  on public.admin_users
  for update
  using (
    exists (
      select 1
      from public.admin_users au
      join public.admin_roles ar on ar.id = au.role_id
      where au.user_id = auth.uid()
        and au.status = 'active'
        and ar.name = 'super_admin'
    )
  );

create policy "Admins can view admin roles"
  on public.admin_roles
  for select
  using (public.is_active_admin());

-- ============================================================
-- Admin customer listing
-- ============================================================

drop function if exists public.admin_list_customers(text);

create function public.admin_list_customers(search_term text default '')
returns table (
  user_id uuid,
  full_name text,
  email text,
  phone text,
  account_number text,
  status text,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  normalized_search text := trim(coalesce(search_term, ''));
begin
  if not public.is_active_admin() then
    raise exception 'Administrator access required';
  end if;

  return query
  select
    p.id,
    p.full_name,
    p.email,
    p.phone,
    w.account_number,
    coalesce(w.status, 'active'),
    p.created_at
  from public.profiles p
  left join lateral (
    select w1.account_number, w1.status
    from public.wallets w1
    where w1.user_id = p.id
    order by w1.created_at asc, w1.id asc
    limit 1
  ) w on true
  where normalized_search = ''
     or p.full_name ilike '%' || normalized_search || '%'
     or p.email ilike '%' || normalized_search || '%'
     or p.phone ilike '%' || normalized_search || '%'
     or w.account_number ilike '%' || normalized_search || '%'
  order by p.created_at desc;
end;
$$;

revoke execute on function public.admin_list_customers(text) from public;
grant execute on function public.admin_list_customers(text) to authenticated;

-- ============================================================
-- Admin customer balances
-- ============================================================

create or replace function public.admin_get_customer_balances(target_user_id uuid)
returns table (
  currency text,
  available numeric,
  pending numeric
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.is_active_admin() then
    raise exception 'Administrator access required';
  end if;

  return query
  select wb.currency, wb.available, wb.pending
  from public.wallet_balances wb
  join public.wallets w on w.id = wb.wallet_id
  where w.user_id = target_user_id
  order by wb.currency;
end;
$$;

revoke execute on function public.admin_get_customer_balances(uuid) from public;
grant execute on function public.admin_get_customer_balances(uuid) to authenticated;

-- ============================================================
-- Admin wallet adjustment
-- ============================================================

create or replace function public.admin_adjust_wallet_balance(
  target_user_id uuid,
  target_currency text,
  adjustment_amount numeric,
  adjustment_direction text,
  adjustment_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  wallet_id_value bigint;
  currency_value text := upper(trim(target_currency));
  amount_value numeric := abs(adjustment_amount);
  direction_value text := lower(trim(adjustment_direction));
  new_balance numeric;
  reference_value text := 'ADM-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 20));
begin
  if not public.is_active_admin() then
    raise exception 'Administrator access required';
  end if;

  if amount_value <= 0 then
    raise exception 'Adjustment amount must be greater than zero';
  end if;

  if direction_value not in ('credit', 'debit') then
    raise exception 'Direction must be credit or debit';
  end if;

  select w.id
  into wallet_id_value
  from public.wallets w
  where w.user_id = target_user_id
  order by w.created_at asc, w.id asc
  limit 1
  for update;

  if wallet_id_value is null then
    raise exception 'Customer wallet not found';
  end if;

  insert into public.wallet_balances (wallet_id, currency)
  values (wallet_id_value, currency_value)
  on conflict (wallet_id, currency) do nothing;

  update public.wallet_balances
  set available = available + case when direction_value = 'credit' then amount_value else -amount_value end,
      updated_at = now()
  where wallet_id = wallet_id_value and currency = currency_value
  returning available into new_balance;

  insert into public.transactions (
    user_id, wallet_id, amount, currency, type, status, description, reference, metadata, completed_at
  ) values (
    target_user_id,
    wallet_id_value,
    case when direction_value = 'credit' then amount_value else -amount_value end,
    currency_value,
    'adjustment',
    'completed',
    coalesce(nullif(trim(adjustment_reason), ''), 'Administrative wallet adjustment'),
    reference_value,
    jsonb_build_object('source', 'admin', 'admin_user_id', auth.uid(), 'direction', direction_value, 'reason', adjustment_reason),
    now()
  );

  return jsonb_build_object(
    'success', true,
    'wallet_id', wallet_id_value,
    'currency', currency_value,
    'direction', direction_value,
    'adjustment_amount', amount_value,
    'new_available_balance', new_balance,
    'reference', reference_value
  );
end;
$$;

revoke execute on function public.admin_adjust_wallet_balance(uuid, text, numeric, text, text) from public;
grant execute on function public.admin_adjust_wallet_balance(uuid, text, numeric, text, text) to authenticated;

-- ============================================================
-- Admin dashboard overview
-- ============================================================

create or replace function public.admin_dashboard_overview()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.is_active_admin() then
    raise exception 'Administrator access required';
  end if;

  return jsonb_build_object(
    'total_users', (select count(*) from public.profiles),
    'total_esim_orders', (select count(*) from public.esim_orders),
    'pending_esim_orders', (select count(*) from public.esim_orders where status in ('pending', 'pending_admin_review')),
    'balances', coalesce((
      select jsonb_agg(jsonb_build_object('currency', currency, 'balance', balance) order by currency)
      from (
        select wb.currency, sum(wb.available) as balance
        from public.wallet_balances wb
        group by wb.currency
      ) totals
    ), '[]'::jsonb),
    'recent_users', coalesce((
      select jsonb_agg(to_jsonb(recent) order by created_at desc)
      from (
        select p.full_name, p.phone, p.created_at
        from public.profiles p
        order by p.created_at desc
        limit 5
      ) recent
    ), '[]'::jsonb),
    'recent_esim_orders', coalesce((
      select jsonb_agg(to_jsonb(recent) order by created_at desc)
      from (
        select e.user_id, e.country_name, e.plan_data, e.status, e.created_at
        from public.esim_orders e
        order by e.created_at desc
        limit 5
      ) recent
    ), '[]'::jsonb),
    'recent_transactions', coalesce((
      select jsonb_agg(to_jsonb(recent) order by created_at desc)
      from (
        select t.type, t.amount, t.currency, t.status, t.created_at
        from public.transactions t
        order by t.created_at desc
        limit 10
      ) recent
    ), '[]'::jsonb)
  );
end;
$$;

revoke execute on function public.admin_dashboard_overview() from public;
grant execute on function public.admin_dashboard_overview() to authenticated;

-- ============================================================
-- Shared admin availability checks
-- ============================================================

grant usage on schema public to authenticated;
grant execute on function public.get_admin_role() to authenticated;
grant execute on function public.is_active_admin() to authenticated;
grant execute on function public.is_super_admin() to authenticated;

notify pgrst, 'reload schema';
