-- Creator submissions repair
-- Run this in the Supabase SQL editor for the connected project.
-- The final NOTIFY refreshes PostgREST's schema cache immediately.

create table if not exists public.creator_submissions (
  id bigint generated by default as identity primary key,
  campaign_id bigint,
  application_id bigint,
  user_id uuid not null references auth.users(id) on delete cascade,
  platform text not null,
  post_url text not null,
  reported_impressions bigint not null default 0,
  status text not null default 'pending'
    check (status in ('pending', 'verified', 'rejected')),
  submitted_at timestamptz not null default now(),
  verified_at timestamptz,
  verified_by uuid references auth.users(id) on delete set null,
  verified_impressions bigint,
  calculated_reward numeric(20, 6),
  payout_status text not null default 'pending'
    check (payout_status in ('pending', 'approved', 'paid', 'rejected')),
  payout_approved_at timestamptz,
  payout_approved_by uuid references auth.users(id) on delete set null,
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists creator_submissions_user_id_idx
  on public.creator_submissions (user_id);

create index if not exists creator_submissions_campaign_id_idx
  on public.creator_submissions (campaign_id);

create index if not exists creator_submissions_submitted_at_idx
  on public.creator_submissions (submitted_at desc);

alter table public.creator_submissions enable row level security;

grant select, insert, update on public.creator_submissions to authenticated;
grant usage, select on sequence public.creator_submissions_id_seq to authenticated;

drop policy if exists "Creators can submit their own work" on public.creator_submissions;
create policy "Creators can submit their own work"
  on public.creator_submissions
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Creators and admins can view submissions" on public.creator_submissions;
create policy "Creators and admins can view submissions"
  on public.creator_submissions
  for select
  to authenticated
  using (
    (select auth.uid()) = user_id
    or (select public.is_active_admin())
  );

drop policy if exists "Admins can update submissions" on public.creator_submissions;
create policy "Admins can update submissions"
  on public.creator_submissions
  for update
  to authenticated
  using ((select public.is_active_admin()))
  with check ((select public.is_active_admin()));

create or replace function public.update_creator_submissions_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists update_creator_submissions_timestamp
  on public.creator_submissions;
create trigger update_creator_submissions_timestamp
before update on public.creator_submissions
for each row execute function public.update_creator_submissions_timestamp();

notify pgrst, 'reload schema';
