-- ============================================================
-- Profiles
-- ============================================================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  phone text,
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists phone text;

alter table public.profiles enable row level security;

create policy "Users can view their own profile"
  on public.profiles
  for select
  using (auth.uid() = id);

create policy "Users can update their own profile"
  on public.profiles
  for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email)
  values (NEW.id, NEW.raw_user_meta_data ->> 'full_name', NEW.email)
  on conflict (id) do update
  set
    full_name = excluded.full_name,
    email = excluded.email;

  return NEW;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

drop function if exists public.handle_new_user();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email)
  values (NEW.id, NEW.raw_user_meta_data ->> 'full_name', NEW.email)
  on conflict (id) do update
  set
    full_name = excluded.full_name,
    email = excluded.email;

  return NEW;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();


-- ============================================================
-- Waitlist signups
-- ============================================================

create table if not exists public.waitlist_signups (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  created_at timestamptz not null default now()
);

alter table public.waitlist_signups enable row level security;

create policy "Anyone can join the waitlist"
  on public.waitlist_signups
  for insert
  with check (true);


-- ============================================================
-- Wallets, balances, and transactions
-- ============================================================

create table if not exists public.wallets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  account_number text unique,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wallet_balances (
  id bigint generated by default as identity primary key,
  wallet_id bigint not null references public.wallets(id) on delete cascade,
  currency text not null,
  available numeric not null default 0,
  pending numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint wallet_balances_unique_currency unique (wallet_id, currency)
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  wallet_id bigint references public.wallets(id) on delete set null,
  amount numeric not null,
  currency text not null,
  type text not null,
  status text not null default 'pending',
  description text,
  reference text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);


-- Keep every new customer ready for wallet operations.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  wallet_id_value bigint;
  account_number_value text;
begin
  insert into public.profiles (id, full_name, email, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.email,
    new.raw_user_meta_data ->> 'phone'
  )
  on conflict (id) do update set
    full_name = coalesce(excluded.full_name, public.profiles.full_name),
    email = coalesce(excluded.email, public.profiles.email),
    phone = coalesce(excluded.phone, public.profiles.phone);

  select w.id
  into wallet_id_value
  from public.wallets w
  where w.user_id = new.id
  order by w.created_at asc, w.id asc
  limit 1;

  if wallet_id_value is null then
    loop
      account_number_value := 'WK' || lpad(floor(random() * 100000000)::bigint::text, 8, '0');
      exit when not exists (
        select 1 from public.wallets w where w.account_number = account_number_value
      );
    end loop;

    insert into public.wallets (user_id, account_number, status)
    values (new.id, account_number_value, 'active')
    returning id into wallet_id_value;
  end if;

  insert into public.wallet_balances (wallet_id, currency)
  values
    (wallet_id_value, 'NGN'), (wallet_id_value, 'USD'),
    (wallet_id_value, 'KES'), (wallet_id_value, 'TZS'),
    (wallet_id_value, 'RWF'), (wallet_id_value, 'USDC'),
    (wallet_id_value, 'USDT'), (wallet_id_value, 'BTC')
  on conflict (wallet_id, currency) do nothing;

  return new;
end;
$$;

create or replace function public.is_active_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users au
    join public.admin_roles ar on ar.id = au.role_id
    where au.user_id = auth.uid()
      and au.status = 'active'
      and ar.name in ('super_admin', 'admin', 'moderator')
  );
$$;

create or replace function public.get_admin_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select ar.name
  from public.admin_users au
  join public.admin_roles ar on ar.id = au.role_id
  where au.user_id = auth.uid()
    and au.status = 'active'
  limit 1;
$$;

create or replace function public.is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users au
    join public.admin_roles ar on ar.id = au.role_id
    where au.user_id = auth.uid()
      and au.status = 'active'
      and ar.name = 'super_admin'
  );
$$;


-- ============================================================
-- eSIM orders
-- ============================================================

create table if not exists public.esim_orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  country_code text not null,
  country_name text not null,
  currency text not null,
  plan_data text not null,
  validity_days integer not null,
  price_usd decimal(10,2) not null,
  customer_price decimal(10,2) not null,
  delivery_email text not null,
  device text not null,
  notes text,
  status text not null default 'pending_admin_review',
  provisioning_target text default 'within_1_hour',
  iccid text,
  qr_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.esim_orders enable row level security;

create policy "Users can view their own eSIM orders"
  on public.esim_orders
  for select
  using (auth.uid() = user_id);

create policy "Users can insert their own eSIM orders"
  on public.esim_orders
  for insert
  with check (auth.uid() = user_id);

-- Admins can view all eSIM orders
create policy "Admins can view all eSIM orders"
  on public.esim_orders
  for select
  using (public.is_active_admin());

-- Admins can update eSIM orders
create policy "Admins can update eSIM orders"
  on public.esim_orders
  for update
  using (public.is_active_admin());

create or replace function public.update_esim_orders_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists update_esim_orders_timestamp on public.esim_orders;
create trigger update_esim_orders_timestamp
before update on public.esim_orders
for each row execute function public.update_esim_orders_timestamp();


-- ============================================================
-- Admin roles & admin users
-- ============================================================

create table if not exists public.admin_roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  permissions jsonb default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_roles enable row level security;

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  role_id bigint not null references public.admin_roles(id) on delete restrict,
  status text not null default 'active' check (status in ('active', 'inactive', 'suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

-- Admins can only view and manage admin records
create policy "Admins can view admin users"
  on public.admin_users
  for select
  using (public.is_active_admin());

create policy "Only super admins can update admin status"
  on public.admin_users
  for update
  using (
    exists (
      select 1
      from public.admin_users au
      join public.admin_roles ar on ar.id = au.role_id
      where au.user_id = auth.uid()
        and au.status = 'active'
        and ar.name = 'super_admin'
    )
  );

-- Admin roles are viewable by all admins
create policy "Admins can view admin roles"
  on public.admin_roles
  for select
  using (public.is_active_admin());

create or replace function public.update_admin_users_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists update_admin_users_timestamp on public.admin_users;
create trigger update_admin_users_timestamp
before update on public.admin_users
for each row execute function public.update_admin_users_timestamp();

-- Insert default admin roles
insert into public.admin_roles (name, description, permissions) values
  ('super_admin', 'Full system access', '["all"]'::jsonb),
  ('admin', 'Standard admin access', '["users", "balances", "esim", "creators"]'::jsonb),
  ('moderator', 'Content moderation', '["creators", "review"]'::jsonb)
on conflict (name) do nothing;





-- ============================================================
-- Admin customer listing
-- ============================================================

drop function if exists public.admin_list_customers(text);

create function public.admin_list_customers(search_term text default '')
returns table (
  user_id uuid,
  full_name text,
  email text,
  phone text,
  account_number text,
  status text,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  normalized_search text := trim(coalesce(search_term, ''));
begin
  if not public.is_active_admin() then
    raise exception 'Administrator access required';
  end if;

  return query
  select
    p.id,
    p.full_name,
    p.email,
    p.phone,
    w.account_number,
    coalesce(w.status, 'active'),
    p.created_at
  from public.profiles p
  left join lateral (
    select w1.account_number, w1.status
    from public.wallets w1
    where w1.user_id = p.id
    order by w1.created_at asc, w1.id asc
    limit 1
  ) w on true
  where normalized_search = ''
     or p.full_name ilike '%' || normalized_search || '%'
     or p.email ilike '%' || normalized_search || '%'
     or p.phone ilike '%' || normalized_search || '%'
     or w.account_number ilike '%' || normalized_search || '%'
  order by p.created_at desc;
end;
$$;

revoke execute on function public.admin_list_customers(text) from public;
grant execute on function public.admin_list_customers(text) to authenticated;


-- ============================================================
-- Admin customer balances
-- ============================================================

create or replace function public.admin_get_customer_balances(target_user_id uuid)
returns table (
  currency text,
  available numeric,
  pending numeric
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.is_active_admin() then
    raise exception 'Administrator access required';
  end if;

  return query
  select wb.currency, wb.available, wb.pending
  from public.wallet_balances wb
  join public.wallets w on w.id = wb.wallet_id
  where w.user_id = target_user_id
  order by wb.currency;
end;
$$;


-- ============================================================
-- Admin wallet adjustment
-- ============================================================

create or replace function public.admin_adjust_wallet_balance(
  target_user_id uuid,
  target_currency text,
  adjustment_amount numeric,
  adjustment_direction text,
  adjustment_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  wallet_id_value bigint;
  currency_value text := upper(trim(target_currency));
  amount_value numeric := abs(adjustment_amount);
  direction_value text := lower(trim(adjustment_direction));
  new_balance numeric;
  reference_value text := 'ADM-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 20));
begin
  if not public.is_active_admin() then
    raise exception 'Administrator access required';
  end if;

  if amount_value <= 0 then
    raise exception 'Adjustment amount must be greater than zero';
  end if;

  if direction_value not in ('credit', 'debit') then
    raise exception 'Direction must be credit or debit';
  end if;

  select w.id
  into wallet_id_value
  from public.wallets w
  where w.user_id = target_user_id
  order by w.created_at asc, w.id asc
  limit 1
  for update;

  if wallet_id_value is null then
    raise exception 'Customer wallet not found';
  end if;

  insert into public.wallet_balances (wallet_id, currency)
  values (wallet_id_value, currency_value)
  on conflict (wallet_id, currency) do nothing;

  update public.wallet_balances
  set available = available + case when direction_value = 'credit' then amount_value else -amount_value end,
      updated_at = now()
  where wallet_id = wallet_id_value and currency = currency_value
  returning available into new_balance;

  insert into public.transactions (
    user_id, wallet_id, amount, currency, type, status, description, reference, metadata, completed_at
  ) values (
    target_user_id,
    wallet_id_value,
    case when direction_value = 'credit' then amount_value else -amount_value end,
    currency_value,
    'adjustment',
    'completed',
    coalesce(nullif(trim(adjustment_reason), ''), 'Administrative wallet adjustment'),
    reference_value,
    jsonb_build_object('source', 'admin', 'admin_user_id', auth.uid(), 'direction', direction_value, 'reason', adjustment_reason),
    now()
  );

  return jsonb_build_object(
    'success', true,
    'wallet_id', wallet_id_value,
    'currency', currency_value,
    'direction', direction_value,
    'adjustment_amount', amount_value,
    'new_available_balance', new_balance,
    'reference', reference_value
  );
end;
$$;

revoke execute on function public.admin_get_customer_balances(uuid) from public;
grant execute on function public.admin_get_customer_balances(uuid) to authenticated;
revoke execute on function public.admin_adjust_wallet_balance(uuid, text, numeric, text, text) from public;
grant execute on function public.admin_adjust_wallet_balance(uuid, text, numeric, text, text) to authenticated;


-- ============================================================
-- Admin dashboard overview
-- ============================================================

create or replace function public.admin_dashboard_overview()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.is_active_admin() then
    raise exception 'Administrator access required';
  end if;

  return jsonb_build_object(
    'total_users', (select count(*) from public.profiles),
    'total_esim_orders', (select count(*) from public.esim_orders),
    'pending_esim_orders', (select count(*) from public.esim_orders where status in ('pending', 'pending_admin_review')),
    'balances', coalesce((
      select jsonb_agg(jsonb_build_object('currency', currency, 'balance', balance) order by currency)
      from (
        select wb.currency, sum(wb.available) as balance
        from public.wallet_balances wb
        group by wb.currency
      ) totals
    ), '[]'::jsonb),
    'recent_users', coalesce((
      select jsonb_agg(to_jsonb(recent) order by created_at desc)
      from (
        select p.full_name, p.phone, p.created_at
        from public.profiles p
        order by p.created_at desc
        limit 5
      ) recent
    ), '[]'::jsonb),
    'recent_esim_orders', coalesce((
      select jsonb_agg(to_jsonb(recent) order by created_at desc)
      from (
        select e.user_id, e.country_name, e.plan_data, e.status, e.created_at
        from public.esim_orders e
        order by e.created_at desc
        limit 5
      ) recent
    ), '[]'::jsonb),
    'recent_transactions', coalesce((
      select jsonb_agg(to_jsonb(recent) order by created_at desc)
      from (
        select t.type, t.amount, t.currency, t.status, t.created_at
        from public.transactions t
        order by t.created_at desc
        limit 10
      ) recent
    ), '[]'::jsonb)
  );
end;
$$;

revoke execute on function public.admin_dashboard_overview() from public;
grant execute on function public.admin_dashboard_overview() to authenticated;


-- ============================================================
-- Financial table protection
-- ============================================================

alter table public.wallets enable row level security;
alter table public.wallet_balances enable row level security;
alter table public.transactions enable row level security;

drop policy if exists "Users can view their own wallets" on public.wallets;
create policy "Users can view their own wallets"
  on public.wallets
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "Users can view their own wallet balances" on public.wallet_balances;
create policy "Users can view their own wallet balances"
  on public.wallet_balances
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.wallets w
      where w.id = wallet_balances.wallet_id
        and w.user_id = auth.uid()
    )
  );

drop policy if exists "Users can view their own transactions" on public.transactions;
create policy "Users can view their own transactions"
  on public.transactions
  for select
  to authenticated
  using (user_id = auth.uid());

grant usage on schema public to authenticated;

grant execute on function public.get_admin_role() to authenticated;
grant execute on function public.is_active_admin() to authenticated;
grant execute on function public.is_super_admin() to authenticated;

notify pgrst, 'reload schema';