-- Run this in Supabase Dashboard > SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists email text;

alter table public.profiles enable row level security;

create policy "Users can view their own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email)
  values (new.id, new.raw_user_meta_data ->> 'full_name', new.email);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create table if not exists public.waitlist_signups (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  created_at timestamptz not null default now()
);

alter table public.waitlist_signups enable row level security;

create policy "Anyone can join the waitlist"
  on public.waitlist_signups for insert
  with check (true);

create table if not exists public.esim_orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  country_code text not null,
  country_name text not null,
  currency text not null,
  plan_data text not null,
  validity_days integer not null,
  price_usd decimal(10,2) not null,
  customer_price decimal(10,2) not null,
  delivery_email text not null,
  device text not null,
  notes text,
  status text not null default 'pending_admin_review',
  provisioning_target text default 'within_1_hour',
  iccid text,
  qr_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.esim_orders enable row level security;

create policy "Users can view their own eSIM orders"
  on public.esim_orders for select
  using (auth.uid() = user_id);

create policy "Users can insert their own eSIM orders"
  on public.esim_orders for insert
  with check (auth.uid() = user_id);

create policy "Admins can view all eSIM orders"
  on public.esim_orders for select
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
      and email in (
        'admin@wakala.com',
        'support@wakala.com'
      )
    )
  );

create policy "Admins can update eSIM orders"
  on public.esim_orders for update
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
      and email in (
        'admin@wakala.com',
        'support@wakala.com'
      )
    )
  );

create or replace function public.update_esim_orders_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists update_esim_orders_timestamp on public.esim_orders;
create trigger update_esim_orders_timestamp
before update on public.esim_orders
for each row execute function public.update_esim_orders_timestamp();
